variable "ami" {}
variable "availability_zone" {}
#variable "availability_zones" {}
variable "instance_type" {}
variable "key_name" {}
variable "subnet_id" {}
#variable "subnet_ids" {}
variable "vpc_security_group_ids" {}
variable "instance_name" {}
variable "user_data" {}
variable "associate_public_ip_address" {}
