name: Terraform Workflow

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      working-directory: 1_devops_infra/2_hub_infra/1_hub_servers

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2


