name: Terraform Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  TF_FOLDER: '1_devops_infra/2_hub_infra/1_hub_servers'  # Updated path

jobs:
  deploy_resources:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          path: ${{ env.TF_FOLDER }}

      - name: List Directory Contents
        working-directory: ${{ env.TF_FOLDER }}
        run: ls -R ${{ env.TF_FOLDER }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        working-directory: ${{ env.TF_FOLDER }}
        run: terraform init

      # Add other Terraform commands such as validate, plan, apply as needed
