name: 1 HUB INFRA - APPLY

on:
  workflow_dispatch:
    inputs:
      tfpath:
        description: 'TF File Path'
        required: false
        default: '1_devops_infra/2_hub_infra/1_hub_servers'
      infra:
        description: 'Jobs to execute (e.g., "apply_network" or "apply_network, apply_sg, apply_nat, apply_jenkins_instance, apply_sonarqube_instance, apply_prometheus_instance, apply_grafana_instance, apply_elk_instance")'
        required: true
        #default: 'apply_network'

jobs:
  tf_code_check:
    name: Hub infra Terraform Validation and Build
    runs-on: ubuntu-latest

    if: ${{ inputs.tfpath }} 

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2.5.0   

    # - name: AWS Credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'  # Access key for AWS authentication
    #     aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'  # Secret key for AWS authentication
    #     aws-region: us-east-1  # AWS region to operate in

    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2.0.2

    - name: Terraform fmt
      id: fmt
      run: |
        echo `pwd`
        echo "tfpath ${{ github.event.inputs.tfpath }}"
        cd ${{ github.event.inputs.tfpath }} 
        echo "** Running Terraform fmt**"
        terraform fmt

    - name: Terraform init
      id: init
      run: |
        echo `pwd`
        echo "tfpath ${{ github.event.inputs.tfpath }}"
        cd ${{ github.event.inputs.tfpath }}
        echo "** Running Terraform Init**"
        terraform init

    - name: Terraform validate
      id: validate
      run: |
        echo `pwd`
        echo "tfpath ${{ github.event.inputs.tfpath }}"
        cd ${{ github.event.inputs.tfpath }}
        echo "** Running Terraform Validate**"
        terraform validate

    - name: Terraform Plan
      id: plan 
      run: |
        echo `pwd`
        echo "tfpath ${{ github.event.inputs.tfpath }}"
        cd ${{ github.event.inputs.tfpath }}
        echo "** Running Terraform Plan**"
        terraform plan --var-file=3hub.tfvars -target module.hub_network
      continue-on-error: true  # Continue to the next step even if there is a plan error

    # - name: Terraform apply
    #   id: Apply 
    #   run: |
    #     echo `pwd`
    #     echo "tfpath ${{ github.event.inputs.tfpath }}"
    #     cd ${{ github.event.inputs.tfpath }}
    #     echo "** Running Terraform apply**"
    #     terraform apply --var-file=3hub.tfvars --auto-approve -target module.hub_network
    #   #ontinue-on-error: true  # Continue to the next step even if there is a plan error

  apply_network:
    name: network
    runs-on: ubuntu-latest

    if: contains(github.event.inputs.infra, 'apply_network')

    steps:
      - name: Terraform apply network
        id: ApplyNetwork
        run: |
          echo `pwd`
          echo "tfpath ${{ github.event.inputs.tfpath }}"
          cd ${{ github.event.inputs.tfpath }}
          echo "** Running Terraform apply network**"
          terraform apply --var-file=3hub.tfvars --auto-approve -target module.hub_network
      # Continue-on-error: true  # Continue to the next step even if there is a plan error

 
  apply_sg:
    name: sg
    runs-on: ubuntu-latest

    if: contains(github.event.inputs.infra, 'apply_sg')

    steps:
      - name: Terraform apply sg
        id: ApplySg
        run: |
          echo `pwd`
          echo "tfpath ${{ github.event.inputs.tfpath }}"
          cd ${{ github.event.inputs.tfpath }}
          echo "** Running Terraform apply sg**"
          terraform apply --var-file=3hub.tfvars --auto-approve -target module.sg
      # Continue-on-error: true  # Continue to the next step even if there is a plan error


  apply_nat:
    name: nat
    runs-on: ubuntu-latest

    if: contains(github.event.inputs.infra, 'apply_nat')

    steps:
      - name: Terraform apply NAT
        id: ApplyNat
        run: |
          echo `pwd`
          echo "tfpath ${{ github.event.inputs.tfpath }}"
          cd ${{ github.event.inputs.tfpath }}
          echo "** Running Terraform apply NAT**"
          terraform apply --var-file=3hub.tfvars --auto-approve -target module.nat
      # Continue-on-error: true  # Continue to the next step even if there is a plan error


  apply_jenkins_instance:
    name: jenkins_instance
    runs-on: ubuntu-latest

    if: contains(github.event.inputs.infra, 'apply_jenkins_instance')

    steps:
      - name: Terraform apply jenkins_instance
        id: ApplyJenkins
        run: |
          echo `pwd`
          echo "tfpath ${{ github.event.inputs.tfpath }}"
          cd ${{ github.event.inputs.tfpath }}
          echo "** Running Terraform apply jenkins**"
          terraform apply --var-file=3hub.tfvars --auto-approve -target module.jenkins_instance
      # Continue-on-error: true  # Continue to the next step even if there is a plan error




  apply_sonarqube_instance:
    name: sonarqube_instance
    runs-on: ubuntu-latest

    if: contains(github.event.inputs.infra, 'apply_sonarqube_instance')

    steps:
      - name: Terraform apply sonarqube_instance
        id: Applysonarqube_instance
        run: |
          echo `pwd`
          echo "tfpath ${{ github.event.inputs.tfpath }}"
          cd ${{ github.event.inputs.tfpath }}
          echo "** Running Terraform apply sonarqube_instance**"
          terraform apply --var-file=3hub.tfvars --auto-approve -target module.sonarqube_instance
      # Continue-on-error: true  # Continue to the next step even if there is a plan error




  apply_prometheus_instance:
    name: prometheus_instance
    runs-on: ubuntu-latest

    if: contains(github.event.inputs.infra, 'apply_prometheus_instance')

    steps:
      - name: Terraform apply prometheus_instance
        id: Applyprometheus_instance
        run: |
          echo `pwd`
          echo "tfpath ${{ github.event.inputs.tfpath }}"
          cd ${{ github.event.inputs.tfpath }}
          echo "** Running Terraform apply prometheus_instance**"
          terraform apply --var-file=3hub.tfvars --auto-approve -target module.prometheus_instance
      # Continue-on-error: true  # Continue to the next step even if there is a plan error





  apply_grafana_instance:
    name: grafana_instance
    runs-on: ubuntu-latest

    if: contains(github.event.inputs.infra, 'apply_grafana_instance')

    steps:
      - name: Terraform apply grafana_instance
        id: Applygrafana_instance
        run: |
          echo `pwd`
          echo "tfpath ${{ github.event.inputs.tfpath }}"
          cd ${{ github.event.inputs.tfpath }}
          echo "** Running Terraform apply grafana_instance**"
          terraform apply --var-file=3hub.tfvars --auto-approve -target module.grafana_instance
      # Continue-on-error: true  # Continue to the next step even if there is a plan error

  apply_elk_instance:
    name: elk_instance
    runs-on: ubuntu-latest

    if: contains(github.event.inputs.infra, 'apply_elk_instance')

    steps:
      - name: Terraform apply elk_instance
        id: Applyelk_instance
        run: |
          echo `pwd`
          echo "tfpath ${{ github.event.inputs.tfpath }}"
          cd ${{ github.event.inputs.tfpath }}
          echo "** Running Terraform apply elk_instance**"
          terraform apply --var-file=3hub.tfvars --auto-approve -target module.elk_instance
      # Continue-on-error: true  # Continue to the next step even if there is a plan error
