name: 1 HUB INFRA - Destroy

on:
  workflow_dispatch:
    # Inputs the workflow expects.
    inputs:
      tfpath:
        description: 'TF File Path'     
        required: false
        default: '1_devops_infra/2_hub_infra/1_hub_servers'

jobs:
  tf_destroy:
    name: Hub infra Terraform Destroy
    runs-on: ubuntu-latest

    if: ${{ inputs.tfpath }} 

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2.5.0   

    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'  # Access key for AWS authentication
        aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'  # Secret key for AWS authentication
        aws-region: us-east-1  # AWS region to operate in

    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2.0.2

     - name: Terraform Init
       id: init
       run: |
        echo `pwd`
        echo "tfpath ${{ github.event.inputs.tfpath }}"
        cd ${{ github.event.inputs.tfpath }}
        echo "** Running Terraform Init**"
        terraform init


    - name: Terraform destroy
      id: destroy 
      run: |
        echo `pwd`
        echo "tfpath ${{ github.event.inputs.tfpath }}"
        cd ${{ github.event.inputs.tfpath }}
        echo "** Running Terraform Destroy**"
        terraform destroy --var-file=3hub.tfvars --auto-approve -target module.backend_s3
      #continue-on-error: true  # Continue to the next step even if there is a destroy error
