name: 1 HUB INFRA

on:
  workflow_dispatch:
  # Uncomment the lines below if you want to trigger on pushes to the main branch
  # push:
  #   branches:
  #     - main

env:
  AWS_REGION: us-east-1
  TF_FOLDER: '1_devops_infra/2_hub_infra/1_hub_servers'


jobs:
  Deploy_Resources:
    runs-on: ubuntu-latest  # Specifies the operating system for the job

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          path: ${{ env.TF_FOLDER }}  # Use 'with' to specify path

      - name: List Directory Contents
        run: ls -R ${{ env.TF_FOLDER }}

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: us-east-1

      - name: Terraform Install
        uses: hashicorp/setup-terraform@v1

      - name: Terraform fmt
        id: fmt
        run: |
          terraform --version  # Prints Terraform version
          terraform fmt  # Formats Terraform code
       # continue-on-error: true  # Continue to the next step even if there are errors

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color  # Validates the Terraform configuration
        #continue-on-error: true  # Continue to the next step even if there are validation errors

      - name: Terraform Plan
        id: plan
        run:  terraform plan -no-color --var-file=3hub.tfvars -target=module.hub_backend_s3  # Creates an execution plan for Terraform changes
       # continue-on-error: true  # Continue to the next step even if there is a plan error

      - name: Terraform Apply
        id: Apply
        run: terraform apply -auto-approve -var-file=3hub.tfvars -target=module.hub_backend_s3  # Applies Terraform changes (auto-approve without asking for confirmation)
       # continue-on-error: true  # Continue to the next step even if there is an apply error
